spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 20
      maximum-pool-size: 500
      idle-timeout: 60000
      max-lifetime: 180000

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

restTemplate:
  thread:
    maxTotal: 200 # max thread number
    maxPerRoute: 100 # max concurrent thread per route

  request:
    socketTimeout: 10000 # the max time waiting for response
    connectTimeout: 2000 # the max time waiting for shaking hand
    connectionRequestTimeout: 2000 # the max time waiting for getting connection from connection pool

task:
  persistent:
    type: jdbc
    username: root
    password: root
    address: jdbc:mysql://localhost:3306/test
    tableName: qualitis_application_task_result
  execute:
    limit_thread: 10
    rule_size: 10

timer:
  thread:
    size: 5
  check:
    period: 10000
  lock:
    zk:
      path: /qualitis/tmp/monitor

zk:
  address: 127.0.0.1
  base_sleep_time: 1000
  max_retries: 3
  session_time_out: 10000
  connection_time_out: 15000
  lock_wait_time: 3

# deprecated
#hive:
#  username: username
#  password: password
#  jdbc:
#    driver-class-name: com.mysql.jdbc.Driver
#    max-pool-size: 50
#    min-pool-size: 2

auth:
  unFilterUrls:
    - /qualitis/api/v1/login/local
    - /qualitis/api/v1/logout
    - /qualitis/api/v1/redirect
  uploadUrls:
    - /qualitis/api/v1/projector/rule/batch/upload/*
    - /qualitis/api/v1/projector/project/batch/upload*

# deprecated
#meta-data:
#  refresh-cron: 55 03 05 * * ?
#  lock-path: /qualitis/tmp/refresh_metadata
#  lock-time: 5

linkis:
  api:
    prefix: api/rest_j/v1
    submitJob: entrance/execute
    status: jobhistory/{id}/get
    runningLog: entrance/{id}/log
    finishLog: filesystem/openLog
    meta_data:
      db_path: datasource/dbs
      table_path: datasource/tables
      column_path: datasource/columns
  log:
    maskKey: task.persistent.username, task.persistent.password
